### PR TITLE
Backbone.js

### PR DESCRIPTION
**Pull request by carlosroec**
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

### CODE REVIEW

**Comment by johnpapa** [comment]
thanks so much! 

please resolve readme conflicts

**Comment by carlosroec** [comment]
@johnpapa done 👍

**Comment by carlosroec** [comment]
@johnpapa all conflicts fixed.

**Comment by johnpapa** [comment]
Thanks.

Do we need jquery and the other libraries to use backbone? Can a hello world backbone app exist without those?

**Comment by carlosroec** [comment]
@johnpapa yes those libraries are required, based on the docs.
"Backbone's only hard dependency is Underscore.js ( >= 1.8.3). For RESTful persistence and DOM manipulation with Backbone.View, include jQuery ( >= 1.11.0)."

**Review by johnpapa — APPROVED** [review]

**Comment by johnpapa** [comment]
@allcontributors please add @carlosroec for code

**Pull request merged**
