### PR TITLE
Added Elm implementation

### PR DESCRIPTION
**Pull request by aelgasser**
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [x] only the most simple basic hello world app
- [x] remove all tests and commands for tests and dependencies for tests
- [x] must say "Hello World" on the main component
- [x] only include the minimal components (1 ideally)
- [x] no routing, not extras whatsoever
- [x] no styling
- [x] nothing else !
- [x] must work by running `npm install` and `npm start` (or equivalent)
- [x] must be in the folder named `<tech-name>`
- [x] add build steps and which folder to serve in the README.md
- [x] verify that the app once built can be served from whatever folder the built assets are placed in
- [x] verify that running `npx http-server <your-folder-to-serve>` works
- [x] verify that a Pull Request doesnt already exist. If it does, feel free to contribue to it.

### CODE REVIEW

**Comment by aelgasser** [comment]
@allcontributors please add @aelgasser for code

**Comment by manekinekko** [comment]
Thanks for your contribution @aelgasser 

Would you mind making these changes before we merge your PR?

- remove `yarn.lock` and use `npm` and `package-lock.json`
- update this repo [`readme.md`](https://github.com/johnpapa/hello-worlds/blob/master/README.md) and include the build steps and which folder to serve in.
- update the `npm run build` script to generate a production build ([see how to create an optimized build](https://github.com/elm/compiler/blob/master/hints/optimize.md))

**Comment by aelgasser** [comment]
@manekinekko You're welcome

I just made the requested changes

**Review by manekinekko — APPROVED** [review]
LGTM

**Pull request merged**
