### PR TITLE
Polymer Hello World

### LINKED ISSUE #33: Polymer App Hello World
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must add to the readme, alphabetically
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`

### PR DESCRIPTION
**Pull request by ksivamuthu**
Polymer App Hello World.

This issue will close #33

### CODE REVIEW

**Comment by johnpapa** [comment]
Can you make it such that I can deploy the contents of a folder (could be the root) and it will work?

Right now it relies on a node_modules folder, which we dont want to deploy.

So mabye put the needed script in the root or a lib folder.

**Comment by johnpapa** [comment]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by johnpapa** [comment]
thanks so much! 

please resolve readme conflicts

**Comment by manekinekko** [comment]
Closing this PR in favor or #100 
Added @ksivamuthu as co-author to the other PR.

**Pull request closed without merging**
