### PR TITLE
Copied Angular project and added Scully

### PR DESCRIPTION
**Pull request by gildotdev**
I had to add routing to the Angular app to make Scully work.

### CODE REVIEW

**Comment by johnpapa** [comment]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by johnpapa** [comment]
wow - does it need the routing? I dont know scully

seems hello world shouldnt need routing.

**Comment by manekinekko** [comment]
@johnpapa Scully generates the static files based on the Angular routing config. If no routes are specified, Scully will not generate the static files.

**Comment by gildotdev** [comment]
Thanks @manekinekko. Yes @johnpapa, without the routes added Scully doesn't know what to generate.

**Comment by gildotdev** [comment]
@allcontributors please add @gilcreque for code

**Review by johnpapa — APPROVED** [review]

**Comment by johnpapa** [comment]
Adds @gilcreque as a contributor for code.

**Pull request merged**
