### PR TITLE
Angular.js

### PR DESCRIPTION
**Pull request by Filini**
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] remove all tests and commands for tests and dependencies for tests
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

### CODE REVIEW

**Comment by Filini** [comment]
This is my first PR on github. If I missed something, please let me know :)

**Review by manekinekko — APPROVED** [review]

**Review by johnpapa — DISMISSED** [review]
Thanks for adding this. Can you include angularjs in the app, and not from a CDN?

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
@Filini any update on this?

**Comment by Filini** [comment]
I added a local file for angular.min.js

Sorry about the delay, I couldn't work on this in the past few days

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
Thank you @Filini I appreciate it 👍

**Pull request merged**
