### PR TITLE
Added jQuery to the mix

### PR DESCRIPTION
**Pull request by rgolea**
It started as a joke. Oh well...

### CODE REVIEW

**Comment by johnpapa** [comment]
thanks for this!

can you make this work without referencing the node_modules folder?

I'd like this to be runnable by serving a folder, even if node_modules isnt there.

**Comment by rgolea** [comment]
@johnpapa not sure if you wanted me to serve it from a cdn or just do a build where I should just copy the insides of jquery to a public folder? Should I still even have a `package.json`?

**Comment by johnpapa** [comment]
self contained app is good. so that it has a copy of jquery in the project. the problem with node_modules is that you dont want to deploy all of those just for jquery. so i'm imagingin the simplest thing is to just have jquery in the root or in a lib folder.

**Comment by johnpapa** [comment]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by manekinekko** [comment]
Hi @rgolea would you mind:
- Update your PR and delete the package.json and package-lock.json files from the jquery folder.
- Rebase your branch and force push to your GitHub repository (this will update your Pull Request):
```
git rebase upstream/master -i
git push -f
```

Thank you for your contribution!

**Comment by johnpapa** [comment]
i'd like each hello world example to be self contained. so each app can point to a "public" folder that could be deployed without referencing anything else. imagine deploying that folder on its own.

for jquery, this means putting the jquery file somewhere in that folder.

@rgolea - can you make this change?

cc @manekinekko

**Review by johnpapa — APPROVED** [review]
CDN will work

**Comment by johnpapa** [comment]
@allcontributors please add @rgolea for code

**Pull request merged**
