### PR TITLE
Add Mithril

### PR DESCRIPTION
**Pull request by wolfhoundjesse**

### CODE REVIEW

**Comment by johnpapa** [comment]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by johnpapa** [comment]
thanks so much! 

please see checklist above

**Review by johnpapa — CHANGES_REQUESTED** [review]
Thanks for the PR.

We need the readme udpated and the index.html is not copied to your dist folder. Can you please modify the build script to do that?

**Comment by wolfhoundjesse** [comment]
I'm on it, thanks!

**Comment by wolfhoundjesse** [comment]
@all-contributors please add @wolfhoundjesse for  code

**Review by johnpapa — APPROVED** [review]

**Review by wolfhoundjesse — COMMENTED** [review]
I just realized you wanted me to update this readme, not the readme in my app. 🤦🏼‍♂️. Thanks, John!

**Comment by johnpapa** [comment]
no worries - I could have been clearer :)

had a lot to review, so I was kinda short.

thanks for the PR

**Pull request merged**
