### PR TITLE
Add Ember version

### LINKED ISSUE #3: Add Ember hello world
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use. 

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must add to the readme
- [ ] must be in the folder named `<tech-name>-app`

### PR DESCRIPTION
**Pull request by sandydoo**
This was generated with the official Ember CLI.

`ember new hello-ember --no-welcome --skip-git`

`no-welcome` skips generating a welcome page for beginners.
`skip-git` skips generating a git repo.

Fixes #3.

### CODE REVIEW

**Comment by johnpapa** [comment]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by sandydoo** [comment]
@all-contributors please add @sandydoo for code

**Comment by GCheung55** [comment]
@sandydoo there's a conflict in the README.md.

**Comment by sandydoo** [comment]
> @sandydoo there's a conflict in the README.md.

@GCheung55, fixed 👍

**Review by johnpapa — APPROVED** [review]

**Comment by Alonski** [comment]
Awesome work @sandydoo !

**Pull request merged**
