### PR TITLE
Scully

### PR DESCRIPTION
**Pull request by afifalfiano**
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] remove all tests and commands for tests and dependencies for tests
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

@allcontributors please add @afifalfiano for scully

### CODE REVIEW

**Comment by manekinekko** [comment]
@afifalfiano could you remove all other changes and leave only the changes related to Scully? One way to do this is to checkout the master branch (make sure it's up to date) and then create a new branch from master. Then add only the Scully changes.

**Comment by afifalfiano** [comment]
I have pulled from the master branch and have made a special branch for scully and in the hello-worlds repository I only changed the readme.md section, is there an issue? @manekinekko

**Comment by manekinekko** [comment]
Hi @afifalfiano Scully example has been added in c015d44cfa34ace9e03ee300677750cf254b39c8. Would you like to contribute a different example?

**Comment by afifalfiano** [comment]
Hi @manekinkekko, I'm sorry, can i suggets to give some example document.md from generate scully, i don't think so that scully project was merge running wihout generate ng scullyio/init:post, on my project just runing npm run build and everything running well😃

**Comment by johnpapa** [comment]
thanks - we had two of these. feel free to add yourself as contrib tho

**Pull request closed without merging**
