### PR TITLE
Meteor app

### PR DESCRIPTION
**Pull request by afifalfiano**
Hello, I'm trying to contribute to making a simple meteor project. Sorry I made a wrong pull request because there is a master branch.

### CODE REVIEW

**Comment by johnpapa** [comment]
you have 2 PRs here ... can you close the one you dont want?

**Comment by johnpapa** [comment]
Please add meteor to the readme, too. follow the pattern in the readme. (see the issue template)

**Comment by afifalfiano** [comment]
Okee, Thank you

**Comment by afifalfiano** [comment]
I

**Comment by afifalfiano** [comment]
For pull requests I choose this, for which there were errors before

**Comment by johnpapa** [comment]
THanks. I removed tests (no need).

I dont see Meteor in the readme. see the others and the issue template for examples. 

By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by afifalfiano** [comment]
@all-contributors please add @afifalfiano for meteor-app

**Pull request closed without merging**
