### PR TITLE
feat: add Eleventy hello world

### LINKED ISSUE #39: Eleventy
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

### PR DESCRIPTION
**Pull request by manekinekko**
Closes #39

By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [x] only the most simple basic hello world app
- [x] remove all tests and commands for tests and dependencies for tests
- [x] must say "Hello World" on the main component
- [x] only include the minimal components (1 ideally)
- [x] no routing, not extras whatsoever
- [x] no styling
- [x] nothing else !
- [x] must work by running `npm install` and `npm start` (or equivalent)
- [x] must be in the folder named `<tech-name>`
- [x] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [x] add build steps and which folder to serve in the README.md, Serve the `public` folder

### CODE REVIEW

**Comment by manekinekko** [comment]
@allcontributors please add @manekinekko for code

**Review by johnpapa — CHANGES_REQUESTED** [review]
I am getting an error when I run npm run build 

```
▶npm run build

> hello-eleventy@1.0.0 build /Users/johnpapa/_git/hello-worlds/eleventy
> eleventy

Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering liquid (and markdown) template ./node_modules/decode-uri-component/readme.md

`TemplateContentRenderError` was thrown
> Having trouble compiling template ./node_modules/decode-uri-component/readme.md

`TemplateContentCompileError` was thrown
> tag ab not found, file:./node_modules/decode-uri-component/readme.md, line:44

`ParseError` was thrown
> tag ab not found

`AssertionError` was thrown:
    AssertionError: tag ab not found
        at assert (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/liquidjs/dist/liquid.common.js:1062:11)
        at Object.parse (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/liquidjs/dist/liquid.common.js:1873:7)
        at Object.construct (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/liquidjs/dist/liquid.common.js:1887:14)
        at parseTag (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/liquidjs/dist/liquid.common.js:2037:16)
        at parseToken (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/liquidjs/dist/liquid.common.js:2021:15)
        at Object.parse (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/liquidjs/dist/liquid.common.js:2012:22)
        at Object.parse$$1 [as parse] (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/liquidjs/dist/liquid.common.js:3420:24)
        at Liquid.compile (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/@11ty/eleventy/src/Engines/Liquid.js:199:29)
        at Markdown.compile (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/@11ty/eleventy/src/Engines/Markdown.js:63:25)
        at TemplateRender.getCompiledTemplate (/Users/johnpapa/_git/hello-worlds/eleventy/node_modules/@11ty/eleventy/src/TemplateRender.js:199:26)
Wrote 0 files in 1.38 seconds (v0.11.0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-eleventy@1.0.0 build: `eleventy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-eleventy@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johnpapa/.npm/_logs/2020-05-22T15_11_47_828Z-debug.log
```

**Comment by manekinekko** [comment]
@johnpapa can you try again? Eleventy was crawling all node_modules. It should be fixed now.

**Review by johnpapa — APPROVED** [review]

**Review by johnpapa — APPROVED** [review]
@allcontributors please add @manekinekko for code

**Comment by johnpapa** [comment]
@allcontributors please add @manekinekko for code

**Pull request merged**
